### ISSUE TITLE
Error syncing invoice: TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by silveltman** [payloadcms/template-ecommerce#13]
1. I completed setup, together with the matching frontend 
2. Added a item to the user cart via de admin panel 
3. went to the cart on the frontend 
4. press checkout
5. got the following error on the frontend AND in the console of the payload backend local server:

[13:13:42] INFO (payload): 🪝 Updating existing order...
[13:13:42] ERROR (payload): - Error syncing invoice: TypeError: Cannot read properties of null (reading 'id')

Is this a known error? I not, I can for sure provide more info on my setup.

The reason why I'm trying to set this up: I want to see the stripe checkout in action and cannot find a demo anywhere. I need to know which payment methods are supported, because here in the Netherlands everyone uses iDeal and not creditcard. 

Answer to this last question would also help a lot, thanks! :)

**Comment by jacobsfletch** [comment]
Hey @silveltman! I can give you some quick answers here. We're using the Stripe Payment Element component on the front-end which _does_ appear to support iDEAL (as long as you set it up in your Stripe account). Check it out: https://stripe.com/docs/payments/payment-element

As for the hooks error, we're actually moving this template entirely over the a "combined" setup, meaning the front-end and back-end will live in the same repo and run on the same server. We've actually already got this work done, and it now lives in the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. We're going to archive this repo soon and start pointing everyone directly to the new template. You should try and spin that template up, its _much_ simpler now.

**Comment by silveltman** [comment]
Thanks for the quick reply @jacobsfletch ! Sounds promising, will definitely try.

I setup where payload and the Drontens app are both hosted together raises some questions tho:
- does this work with multi-tenant?
- hoe does Payload cloud pricing work with a setup like this, or with multi tenant in general?
- does this work with an Astro app too?
- if so, does it support static and hybrid/dat rendering?
- and lastly, how would performance compare to a hosting solution like Vercel?

Lot of questions, but I cant find answers on these via the docs

**Comment by silveltman** [comment]
Just set it up and got it to work very smoothly! However, it only seems to support creditcard payments. Please have a look at the below screenshot:
![Screenshot 2023-08-22 at 09 30 19](https://github.com/payloadcms/template-ecommerce/assets/52583398/9d43dbe4-0897-41ad-9841-3338f4896b54)

I have enabled all payment methods in my stripe account.

**Comment by jacobsfletch** [comment]
Hey @silveltman, looks like you've got everything spun it, very exciting! Here's some quick answers for you:

- Does this work with multi-tenant? This might get tricky because each front-end will require it's own set of environment variables, i.e. Stripe keys, etc. I'm sure it's possible, but another complexity to this would be serving a separate instance for each tenant's front-end from using same codebase on the same server.
- How does Payload Cloud pricing work with a setup like this, or with multi tenant in general? Cloud pricing is completely standard, no strings attached. You can do whatever you wish on your server within the boundaries of your hardware. Hosting multiple tenants might require more computational power.
- Does this work with an Astro app too? Payload itself is headless so you can wire in any front-end framework that you wish. There is a handy `yarn eject` script in the repo to quickly remove Next.js from the repo so you can implement to your own front-end from scratch.
- If so, does it support static and hybrid/dat rendering? Absolutely, just depends on how you set up your front-end. With Next.js you can setup your site to be server-rendered, static, or hybrid. To Payload, it's all the same. You just hit the exact same APIs.
- And lastly, how would performance compare to a hosting solution like Vercel? Vercel is a great platform, especially the globally distributed CDN and mature interface. Hosting static front-ends on Vercel is a terrific solution, but you will likely not notice a difference in performance until your project reaches large scale.

This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
