### ISSUE TITLE
Cart components loads into "Create first user" screen.

### ISSUE THREAD

**Issue by soullessxo** [payloadcms/template-ecommerce#2]
![image](https://user-images.githubusercontent.com/104219168/233795195-dc8307d0-ea07-448a-853b-6c8e16085558.png)
That causes ERROR (payload): UnauthorizedError: Unauthorized, you must be logged in to make this request.
I am running docker compose and using mongo 4.4.6 tho.

**Comment by jacobsfletch** [comment]
@8blvck the cart field appearing on the "create first user" screen is expected, this is because it is a user field. But it is not required so you shouldn't have any validation issues here if you leave this field blank. The "unauthorized" warning you're seeing is specific to auth. It sounds to me like your app is not attaching the payload token as a cookie after login, my guess is that the docker config is missing some environment variables.

I'm pulling this down right now and should have a fix shortly 🔧

**Comment by jacobsfletch** [comment]
@8blvck all set, this was fixed with https://github.com/payloadcms/template-ecommerce/pull/3/commits/01ca51f8ab06f2dc8d4d6ce1ec0653f640dbb48c in PR #3. THANK YOU for reporting this! 🙌
