### ISSUE TITLE
Template already seems to come with an admin account, but docs claim you should create one

### ISSUE THREAD

**Issue by mgielda** [payloadcms/template-ecommerce#6]
Maybe of course I am doing sth wrong, but going to http://localhost:8000/admin took me straight to the login page (and not to the creation of the first user). I was about to give up but then decided to look up other examples, and for those, step 5 is: `Login with email dev@payloadcms.com and password test` - tried that and it worked.

Is there something I am overlooking?

I tried the Docker images, and failed, and then installed mongodb by hand.

**Comment by mgielda** [comment]
I actually did a "seed" in the meantime, can it be that this created an admin account?

Even if that's the case, prior to that I did not have an option to create an account.

**Comment by absolutegravitas** [comment]
same -- can see in the MongoDB users collection a user with dev@payloadcms.com already created
![image](https://github.com/payloadcms/template-ecommerce/assets/124488796/05215c8e-7ca8-4c9f-9bf6-62a705ce570e)

**Comment by jacobsfletch** [comment]
Hey @mgielda and @absolutegravitas thank you both for taking the time to bring this up. This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. This latest codebase does _not_ seed the initial user like it does here, so this is no longer an issue. Go ahead and clone down the latest code and give it a shot! I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
