### ISSUE TITLE
docker-compose up doesnt produce admin/login screen

### ISSUE THREAD

**Issue by absolutegravitas** [payloadcms/template-ecommerce#9]
attempted to follow instructions to run payload via docker-compose up after updating .env
ENV file is valid, mongo atlas db also valid

![image](https://github.com/payloadcms/template-ecommerce/assets/124488796/5fecc391-c822-4d88-8944-211f1a207caa)
![image](https://github.com/payloadcms/template-ecommerce/assets/124488796/63c83894-239d-4465-9def-7b1ea3bdabb6)
![image](https://github.com/payloadcms/template-ecommerce/assets/124488796/fc6828e1-8125-485a-8add-0fa71f40252f)

**Comment by absolutegravitas** [comment]
yarn & yarn dev appear to work
![image](https://github.com/payloadcms/template-ecommerce/assets/124488796/6e7c5897-a02f-436f-b3d2-9750725e3ebc)

**Comment by jacobsfletch** [comment]
Hey @absolutegravitas thanks for bringing this up! This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. I'm going to close this PR out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
